version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '80:3000'
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
