import { Seeder, SeederFactoryManager } from 'typeorm-extension';
import { DataSource, QueryRunner } from 'typeorm';
import { Region } from 'src/entities/region/region.entity';
import { ClassConstructor } from 'class-transformer';
import { BaseTimeEntity } from '../baseTime.entity';
import { Country } from 'src/entities/country/country.entity';
import { Location } from 'src/entities/location/location.entity';
import { Department } from 'src/entities/department/department.entity';
import { Job } from 'src/entities/job/job.entity';
import { Employee } from 'src/entities/employee/employee.entity';
import { JobHistory } from 'src/entities/job-history/job-history.entity';

export default class InitialDataSeeder implements Seeder {
  public async run(
    dataSource: DataSource,
    _factoryManager: SeederFactoryManager,
  ): Promise<any> {
    const regionList = [
      { regionId: 1, regionName: 'Europe' },
      { regionId: 2, regionName: 'Americas' },
      { regionId: 3, regionName: 'Asia' },
      { regionId: 4, regionName: 'Middle East and Africa' },
    ];

    const countryList = [
      { countryId: 'IT', countryName: 'Italy', regionId: 1 },
      { countryId: 'JP', countryName: 'Japan', regionId: 3 },
      { countryId: 'US', countryName: 'United States of America', regionId: 2 },
      { countryId: 'CA', countryName: 'Canada', regionId: 2 },
      { countryId: 'CN', countryName: 'China', regionId: 3 },
      { countryId: 'IN', countryName: 'India', regionId: 3 },
      { countryId: 'AU', countryName: 'Australia', regionId: 3 },
      { countryId: 'ZW', countryName: 'Zimbabwe', regionId: 4 },
      { countryId: 'SG', countryName: 'Singapore', regionId: 3 },
      { countryId: 'UK', countryName: 'United Kingdom', regionId: 1 },
      { countryId: 'FR', countryName: 'France', regionId: 1 },
      { countryId: 'DE', countryName: 'Germany', regionId: 1 },
      { countryId: 'ZM', countryName: 'Zambia', regionId: 4 },
      { countryId: 'EG', countryName: 'Egypt', regionId: 4 },
      { countryId: 'BR', countryName: 'Brazil', regionId: 2 },
      { countryId: 'CH', countryName: 'Switzerland', regionId: 1 },
      { countryId: 'NL', countryName: 'Netherlands', regionId: 1 },
      { countryId: 'MX', countryName: 'Mexico', regionId: 2 },
      { countryId: 'KW', countryName: 'Kuwait', regionId: 4 },
      { countryId: 'IL', countryName: 'Israel', regionId: 4 },
      { countryId: 'DK', countryName: 'Denmark', regionId: 1 },
      { countryId: 'HK', countryName: 'HongKong', regionId: 3 },
      { countryId: 'NG', countryName: 'Nigeria', regionId: 4 },
      { countryId: 'AR', countryName: 'Argentina', regionId: 2 },
      { countryId: 'BE', countryName: 'Belgium', regionId: 1 },
      // Add other countries...
    ];

    const locationList = [
      {
        locationId: 1000,
        streetAddress: '1297 Via Cola di Rie',
        postalCode: '00989',
        city: 'Roma',
        stateProvince: null,
        countryId: 'IT',
      },
      {
        locationId: 1700,
        streetAddress: '2004 Charade Rd',
        postalCode: '98199',
        city: 'Seattle',
        stateProvince: 'Washington',
        countryId: 'US',
      },
      {
        locationId: 1100,
        streetAddress: '93091 Calle della Testa',
        postalCode: '10934',
        city: 'Venice',
        stateProvince: null,
        countryId: 'IT',
      },
      {
        locationId: 1200,
        streetAddress: '2017 Shinjuku-ku',
        postalCode: '1689',
        city: 'Tokyo',
        stateProvince: 'Tokyo Prefecture',
        countryId: 'JP',
      },
      {
        locationId: 1300,
        streetAddress: '9450 Kamiya-cho',
        postalCode: '6823',
        city: 'Hiroshima',
        stateProvince: null,
        countryId: 'JP',
      },
      {
        locationId: 1400,
        streetAddress: '2014 Jabberwocky Rd',
        postalCode: '26192',
        city: 'Southlake',
        stateProvince: 'Texas',
        countryId: 'US',
      },
      {
        locationId: 1500,
        streetAddress: '2011 Interiors Blvd',
        postalCode: '99236',
        city: 'South San Francisco',
        stateProvince: 'California',
        countryId: 'US',
      },
      {
        locationId: 1600,
        streetAddress: '2007 Zagora St',
        postalCode: '50090',
        city: 'South Brunswick',
        stateProvince: 'New Jersey',
        countryId: 'US',
      },
      {
        locationId: 1800,
        streetAddress: '147 Spadina Ave',
        postalCode: 'M5V 2L7',
        city: 'Toronto',
        stateProvince: 'Ontario',
        countryId: 'CA',
      },
      {
        locationId: 1900,
        streetAddress: '6092 Boxwood St',
        postalCode: 'YSW 9T2',
        city: 'Whitehorse',
        stateProvince: 'Yukon',
        countryId: 'CA',
      },
      {
        locationId: 2000,
        streetAddress: '40-5-12 Laogianggen',
        postalCode: '190518',
        city: 'Beijing',
        stateProvince: null,
        countryId: 'CN',
      },
      {
        locationId: 2100,
        streetAddress: '1298 Vileparle (E)',
        postalCode: '490231',
        city: 'Bombay',
        stateProvince: 'Maharashtra',
        countryId: 'IN',
      },
      {
        locationId: 2200,
        streetAddress: '12-98 Victoria Street',
        postalCode: '2901',
        city: 'Sydney',
        stateProvince: 'New South Wales',
        countryId: 'AU',
      },
      {
        locationId: 2300,
        streetAddress: '198 Clementi North',
        postalCode: '540198',
        city: 'Singapore',
        stateProvince: null,
        countryId: 'SG',
      },
      {
        locationId: 2400,
        streetAddress: '8204 Arthur St',
        postalCode: null,
        city: 'London',
        stateProvince: null,
        countryId: 'UK',
      },
      {
        locationId: 2500,
        streetAddress: 'Magdalen Centre, The Oxford Science Park',
        postalCode: 'OX9 9ZB',
        city: 'Oxford',
        stateProvince: 'Oxford',
        countryId: 'UK',
      },
      {
        locationId: 2600,
        streetAddress: '9702 Chester Road',
        postalCode: '09629850293',
        city: 'Stretford',
        stateProvince: 'Manchester',
        countryId: 'UK',
      },
      {
        locationId: 2700,
        streetAddress: 'Schwanthalerstr. 7031',
        postalCode: '80925',
        city: 'Munich',
        stateProvince: 'Bavaria',
        countryId: 'DE',
      },
      {
        locationId: 2800,
        streetAddress: 'Rua Frei Caneca 1360 ',
        postalCode: '01307-002',
        city: 'Sao Paulo',
        stateProvince: 'Sao Paulo',
        countryId: 'BR',
      },
      {
        locationId: 2900,
        streetAddress: '20 Rue des Corps-Saints',
        postalCode: '1730',
        city: 'Geneva',
        stateProvince: 'Geneve',
        countryId: 'CH',
      },
      {
        locationId: 3000,
        streetAddress: 'Murtenstrasse 921',
        postalCode: '3095',
        city: 'Bern',
        stateProvince: 'BE',
        countryId: 'CH',
      },
      {
        locationId: 3100,
        streetAddress: 'Pieter Breughelstraat 837',
        postalCode: '3029SK',
        city: 'Utrecht',
        stateProvince: 'Utrecht',
        countryId: 'NL',
      },
      {
        locationId: 3200,
        streetAddress: 'Mariano Escobedo 9991',
        postalCode: '11932',
        city: 'Mexico City',
        stateProvince: 'Distrito Federal',
        countryId: 'MX',
      },
    ];

    const departmentList = [
      {
        departmentId: 10,
        departmentName: 'Administration',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 20,
        departmentName: 'Marketing',
        managerId: null,
        locationId: 1800,
      },
      {
        departmentId: 30,
        departmentName: 'Purchasing',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 40,
        departmentName: 'Human Resources',
        managerId: null,
        locationId: 2400,
      },
      {
        departmentId: 50,
        departmentName: 'Shipping',
        managerId: null,
        locationId: 1500,
      },
      {
        departmentId: 60,
        departmentName: 'IT',
        managerId: null,
        locationId: 1400,
      },
      {
        departmentId: 70,
        departmentName: 'Public Relations',
        managerId: null,
        locationId: 2700,
      },
      {
        departmentId: 80,
        departmentName: 'Sales',
        managerId: null,
        locationId: 2500,
      },
      {
        departmentId: 90,
        departmentName: 'Executive',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 100,
        departmentName: 'Finance',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 110,
        departmentName: 'Accounting',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 120,
        departmentName: 'Treasury',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 130,
        departmentName: 'Corporate Tax',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 140,
        departmentName: 'Control And Credit',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 150,
        departmentName: 'Shareholder Services',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 160,
        departmentName: 'Benefits',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 170,
        departmentName: 'Manufacturing',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 180,
        departmentName: 'Construction',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 190,
        departmentName: 'Contracting',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 200,
        departmentName: 'Operations',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 210,
        departmentName: 'IT Support',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 220,
        departmentName: 'NOC',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 230,
        departmentName: 'IT Helpdesk',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 240,
        departmentName: 'Government Sales',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 250,
        departmentName: 'Retail Sales',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 260,
        departmentName: 'Recruiting',
        managerId: null,
        locationId: 1700,
      },
      {
        departmentId: 270,
        departmentName: 'Payroll',
        managerId: null,
        locationId: 1700,
      },
    ];

    const jobList = [
      {
        jobId: 'AD_PRES',
        jobTitle: 'President',
        minSalary: 20000,
        maxSalary: 40000,
      },
      {
        jobId: 'AD_VP',
        jobTitle: 'Administration Vice President',
        minSalary: 15000,
        maxSalary: 30000,
      },
      {
        jobId: 'AD_ASST',
        jobTitle: 'Administration Assistant',
        minSalary: 3000,
        maxSalary: 6000,
      },
      {
        jobId: 'FI_MGR',
        jobTitle: 'Finance Manager',
        minSalary: 8200,
        maxSalary: 16000,
      },
      {
        jobId: 'FI_ACCOUNT',
        jobTitle: 'Accountant',
        minSalary: 4200,
        maxSalary: 9000,
      },
      {
        jobId: 'AC_MGR',
        jobTitle: 'Accounting Manager',
        minSalary: 8200,
        maxSalary: 16000,
      },
      {
        jobId: 'AC_ACCOUNT',
        jobTitle: 'Public Accountant',
        minSalary: 4200,
        maxSalary: 9000,
      },
      {
        jobId: 'SA_MAN',
        jobTitle: 'Sales Manager',
        minSalary: 10000,
        maxSalary: 20000,
      },
      {
        jobId: 'SA_REP',
        jobTitle: 'Sales Representative',
        minSalary: 6000,
        maxSalary: 12000,
      },
      {
        jobId: 'PU_MAN',
        jobTitle: 'Purchasing Manager',
        minSalary: 8000,
        maxSalary: 15000,
      },
      {
        jobId: 'PU_CLERK',
        jobTitle: 'Purchasing Clerk',
        minSalary: 2500,
        maxSalary: 5500,
      },
      {
        jobId: 'ST_MAN',
        jobTitle: 'Stock Manager',
        minSalary: 5500,
        maxSalary: 8500,
      },
      {
        jobId: 'ST_CLERK',
        jobTitle: 'Stock Clerk',
        minSalary: 2000,
        maxSalary: 5000,
      },
      {
        jobId: 'SH_CLERK',
        jobTitle: 'Shipping Clerk',
        minSalary: 2500,
        maxSalary: 5500,
      },
      {
        jobId: 'IT_PROG',
        jobTitle: 'Programmer',
        minSalary: 4000,
        maxSalary: 10000,
      },
      {
        jobId: 'MK_MAN',
        jobTitle: 'Marketing Manager',
        minSalary: 9000,
        maxSalary: 15000,
      },
      {
        jobId: 'MK_REP',
        jobTitle: 'Marketing Representative',
        minSalary: 4000,
        maxSalary: 9000,
      },
      {
        jobId: 'HR_REP',
        jobTitle: 'Human Resources Representative',
        minSalary: 4000,
        maxSalary: 9000,
      },
      {
        jobId: 'PR_REP',
        jobTitle: 'Public Relations Representative',
        minSalary: 4500,
        maxSalary: 10500,
      },
    ];

    const employeeList = [
      {
        employeeId: 100,
        firstName: 'Steven',
        lastName: 'King',
        email: 'SKING',
        phoneNumber: '515.123.4567',
        hireDate: new Date('1987-06-17'),
        jobId: 'AD_PRES',
        salary: 24000,
        commissionPct: null,
        managerId: null,
        departmentId: 90,
      },
      {
        employeeId: 101,
        firstName: 'Neena',
        lastName: 'Kochhar',
        email: 'NKOCHHAR',
        phoneNumber: '515.123.4568',
        hireDate: new Date('1989-09-21'),
        jobId: 'AD_VP',
        salary: 17000,
        commissionPct: null,
        managerId: 100,
        departmentId: 90,
      },
      {
        employeeId: 102,
        firstName: 'Lex',
        lastName: 'De Haan',
        email: 'LDEHAAN',
        phoneNumber: '515.123.4569',
        hireDate: new Date('1993-01-13'),
        jobId: 'AD_VP',
        salary: 17000,
        commissionPct: null,
        managerId: 100,
        departmentId: 90,
      },
      {
        employeeId: 103,
        firstName: 'Alexander',
        lastName: 'Hunold',
        email: 'AHUNOLD',
        phoneNumber: '590.423.4567',
        hireDate: new Date('1990-01-03'),
        jobId: 'IT_PROG',
        salary: 9000,
        commissionPct: null,
        managerId: 102,
        departmentId: 60,
      },
      {
        employeeId: 104,
        firstName: 'Bruce',
        lastName: 'Ernst',
        email: 'BERNST',
        phoneNumber: '590.423.4568',
        hireDate: new Date('1991-05-21'),
        jobId: 'IT_PROG',
        salary: 6000,
        commissionPct: null,
        managerId: 103,
        departmentId: 60,
      },
      {
        employeeId: 105,
        firstName: 'David',
        lastName: 'Austin',
        email: 'DAUSTIN',
        phoneNumber: '590.423.4569',
        hireDate: new Date('1997-06-25'),
        jobId: 'IT_PROG',
        salary: 4800,
        commissionPct: null,
        managerId: 103,
        departmentId: 60,
      },
      {
        employeeId: 106,
        firstName: 'Valli',
        lastName: 'Pataballa',
        email: 'VPATABAL',
        phoneNumber: '590.423.4560',
        hireDate: new Date('1998-02-05'),
        jobId: 'IT_PROG',
        salary: 4800,
        commissionPct: null,
        managerId: 103,
        departmentId: 60,
      },
      {
        employeeId: 107,
        firstName: 'Diana',
        lastName: 'Lorentz',
        email: 'DLORENTZ',
        phoneNumber: '590.423.5567',
        hireDate: new Date('1999-02-07'),
        jobId: 'IT_PROG',
        salary: 4200,
        commissionPct: null,
        managerId: 103,
        departmentId: 60,
      },
      {
        employeeId: 108,
        firstName: 'Nancy',
        lastName: 'Greenberg',
        email: 'NGREENBE',
        phoneNumber: '515.124.4569',
        hireDate: new Date('1994-08-17'),
        jobId: 'FI_MGR',
        salary: 12000,
        commissionPct: null,
        managerId: 101,
        departmentId: 100,
      },
      {
        employeeId: 109,
        firstName: 'Daniel',
        lastName: 'Faviet',
        email: 'DFAVIET',
        phoneNumber: '515.124.4169',
        hireDate: new Date('1994-08-16'),
        jobId: 'FI_ACCOUNT',
        salary: 9000,
        commissionPct: null,
        managerId: 108,
        departmentId: 100,
      },
      {
        employeeId: 110,
        firstName: 'John',
        lastName: 'Chen',
        email: 'JCHEN',
        phoneNumber: '515.124.4269',
        hireDate: new Date('1997-09-28'),
        jobId: 'FI_ACCOUNT',
        salary: 8200,
        commissionPct: null,
        managerId: 108,
        departmentId: 100,
      },
      {
        employeeId: 111,
        firstName: 'Ismael',
        lastName: 'Sciarra',
        email: 'ISCIARRA',
        phoneNumber: '515.124.4369',
        hireDate: new Date('1997-09-30'),
        jobId: 'FI_ACCOUNT',
        salary: 7700,
        commissionPct: null,
        managerId: 108,
        departmentId: 100,
      },
      {
        employeeId: 112,
        firstName: 'Jose Manuel',
        lastName: 'Urman',
        email: 'JMURMAN',
        phoneNumber: '515.124.4469',
        hireDate: new Date('1998-03-07'),
        jobId: 'FI_ACCOUNT',
        salary: 7800,
        commissionPct: null,
        managerId: 108,
        departmentId: 100,
      },
      {
        employeeId: 113,
        firstName: 'Luis',
        lastName: 'Popp',
        email: 'LPOPP',
        phoneNumber: '515.124.4567',
        hireDate: new Date('1999-12-07'),
        jobId: 'FI_ACCOUNT',
        salary: 6900,
        commissionPct: null,
        managerId: 108,
        departmentId: 100,
      },
      {
        employeeId: 114,
        firstName: 'Den',
        lastName: 'Raphaely',
        email: 'DRAPHEAL',
        phoneNumber: '515.127.4561',
        hireDate: new Date('1994-12-07'),
        jobId: 'PU_MAN',
        salary: 11000,
        commissionPct: null,
        managerId: 100,
        departmentId: 30,
      },
      {
        employeeId: 115,
        firstName: 'Alexander',
        lastName: 'Khoo',
        email: 'AKHOO',
        phoneNumber: '515.127.4562',
        hireDate: new Date('1995-05-18'),
        jobId: 'PU_CLERK',
        salary: 3100,
        commissionPct: null,
        managerId: 114,
        departmentId: 30,
      },
      {
        employeeId: 116,
        firstName: 'Shelli',
        lastName: 'Baida',
        email: 'SBAIDA',
        phoneNumber: '515.127.4563',
        hireDate: new Date('1997-12-24'),
        jobId: 'PU_CLERK',
        salary: 2900,
        commissionPct: null,
        managerId: 114,
        departmentId: 30,
      },
      {
        employeeId: 117,
        firstName: 'Sigal',
        lastName: 'Tobias',
        email: 'STOBIAS',
        phoneNumber: '515.127.4564',
        hireDate: new Date('1997-07-24'),
        jobId: 'PU_CLERK',
        salary: 2800,
        commissionPct: null,
        managerId: 114,
        departmentId: 30,
      },
      {
        employeeId: 118,
        firstName: 'Guy',
        lastName: 'Himuro',
        email: 'GHIMURO',
        phoneNumber: '515.127.4565',
        hireDate: new Date('1998-11-15'),
        jobId: 'PU_CLERK',
        salary: 2600,
        commissionPct: null,
        managerId: 114,
        departmentId: 30,
      },
      {
        employeeId: 119,
        firstName: 'Karen',
        lastName: 'Colmenares',
        email: 'KCOLMENA',
        phoneNumber: '515.127.4566',
        hireDate: new Date('1999-08-10'),
        jobId: 'PU_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 114,
        departmentId: 30,
      },
      {
        employeeId: 120,
        firstName: 'Matthew',
        lastName: 'Weiss',
        email: 'MWEISS',
        phoneNumber: '650.123.1234',
        hireDate: new Date('1996-07-18'),
        jobId: 'ST_MAN',
        salary: 8000,
        commissionPct: null,
        managerId: 100,
        departmentId: 50,
      },
      {
        employeeId: 121,
        firstName: 'Adam',
        lastName: 'Fripp',
        email: 'AFRIPP',
        phoneNumber: '650.123.2234',
        hireDate: new Date('1997-04-10'),
        jobId: 'ST_MAN',
        salary: 8200,
        commissionPct: null,
        managerId: 100,
        departmentId: 50,
      },
      {
        employeeId: 122,
        firstName: 'Payam',
        lastName: 'Kaufling',
        email: 'PKAUFLIN',
        phoneNumber: '650.123.3234',
        hireDate: new Date('1995-05-01'),
        jobId: 'ST_MAN',
        salary: 7900,
        commissionPct: null,
        managerId: 100,
        departmentId: 50,
      },
      {
        employeeId: 123,
        firstName: 'Shanta',
        lastName: 'Vollman',
        email: 'SVOLLMAN',
        phoneNumber: '650.123.4234',
        hireDate: new Date('1997-10-10'),
        jobId: 'ST_MAN',
        salary: 6500,
        commissionPct: null,
        managerId: 100,
        departmentId: 50,
      },
      {
        employeeId: 124,
        firstName: 'Kevin',
        lastName: 'Mourgos',
        email: 'KMOURGOS',
        phoneNumber: '650.123.5234',
        hireDate: new Date('1999-11-16'),
        jobId: 'ST_MAN',
        salary: 5800,
        commissionPct: null,
        managerId: 100,
        departmentId: 50,
      },
      {
        employeeId: 125,
        firstName: 'Julia',
        lastName: 'Nayer',
        email: 'JNAYER',
        phoneNumber: '650.124.1214',
        hireDate: new Date('1997-07-16'),
        jobId: 'ST_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 126,
        firstName: 'Irene',
        lastName: 'Mikkilineni',
        email: 'IMIKKILI',
        phoneNumber: '650.124.1224',
        hireDate: new Date('1998-09-28'),
        jobId: 'ST_CLERK',
        salary: 2700,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 127,
        firstName: 'James',
        lastName: 'Landry',
        email: 'JLANDRY',
        phoneNumber: '650.124.1334',
        hireDate: new Date('1999-01-14'),
        jobId: 'ST_CLERK',
        salary: 2400,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 128,
        firstName: 'Steven',
        lastName: 'Markle',
        email: 'SMARKLE',
        phoneNumber: '650.124.1434',
        hireDate: new Date('2000-03-08'),
        jobId: 'ST_CLERK',
        salary: 2200,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 129,
        firstName: 'Laura',
        lastName: 'Bissot',
        email: 'LBISSOT',
        phoneNumber: '650.124.5234',
        hireDate: new Date('1997-08-20'),
        jobId: 'ST_CLERK',
        salary: 3300,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 130,
        firstName: 'Mozhe',
        lastName: 'Atkinson',
        email: 'MATKINSO',
        phoneNumber: '650.124.6234',
        hireDate: new Date('1997-10-30'),
        jobId: 'ST_CLERK',
        salary: 2800,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 131,
        firstName: 'James',
        lastName: 'Marlow',
        email: 'JAMRLOW',
        phoneNumber: '650.124.7234',
        hireDate: new Date('1997-02-16'),
        jobId: 'ST_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 132,
        firstName: 'TJ',
        lastName: 'Olson',
        email: 'TJOLSON',
        phoneNumber: '650.124.8234',
        hireDate: new Date('1999-04-10'),
        jobId: 'ST_CLERK',
        salary: 2100,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 133,
        firstName: 'Jason',
        lastName: 'Mallin',
        email: 'JMALLIN',
        phoneNumber: '650.127.1934',
        hireDate: new Date('1996-06-14'),
        jobId: 'ST_CLERK',
        salary: 3300,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 134,
        firstName: 'Michael',
        lastName: 'Rogers',
        email: 'MROGERS',
        phoneNumber: '650.127.1834',
        hireDate: new Date('1998-08-26'),
        jobId: 'ST_CLERK',
        salary: 2900,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 135,
        firstName: 'Ki',
        lastName: 'Gee',
        email: 'KGEE',
        phoneNumber: '650.127.1734',
        hireDate: new Date('1999-12-12'),
        jobId: 'ST_CLERK',
        salary: 2400,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 136,
        firstName: 'Hazel',
        lastName: 'Philtanker',
        email: 'HPHILTAN',
        phoneNumber: '650.127.1634',
        hireDate: new Date('2000-02-06'),
        jobId: 'ST_CLERK',
        salary: 2200,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 137,
        firstName: 'Renske',
        lastName: 'Ladwig',
        email: 'RLADWIG',
        phoneNumber: '650.121.1234',
        hireDate: new Date('1995-07-14'),
        jobId: 'ST_CLERK',
        salary: 3600,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 138,
        firstName: 'Stephen',
        lastName: 'Stiles',
        email: 'SSTILES',
        phoneNumber: '650.121.2034',
        hireDate: new Date('1997-10-26'),
        jobId: 'ST_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 139,
        firstName: 'John',
        lastName: 'Seo',
        email: 'JSEO',
        phoneNumber: '650.121.2019',
        hireDate: new Date('1998-02-12'),
        jobId: 'ST_CLERK',
        salary: 2700,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 140,
        firstName: 'Joshua',
        lastName: 'Patel',
        email: 'JPATEL',
        phoneNumber: '650.121.1834',
        hireDate: new Date('1998-04-06'),
        jobId: 'ST_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 141,
        firstName: 'Trenna',
        lastName: 'Rajs',
        email: 'TRAJS',
        phoneNumber: '650.121.8009',
        hireDate: new Date('1995-10-17'),
        jobId: 'ST_CLERK',
        salary: 3500,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 142,
        firstName: 'Curtis',
        lastName: 'Davies',
        email: 'CDAVIES',
        phoneNumber: '650.121.2994',
        hireDate: new Date('1997-01-29'),
        jobId: 'ST_CLERK',
        salary: 3100,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 143,
        firstName: 'Randall',
        lastName: 'Matos',
        email: 'RMATOS',
        phoneNumber: '650.121.2874',
        hireDate: new Date('1998-03-15'),
        jobId: 'ST_CLERK',
        salary: 2600,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 144,
        firstName: 'Peter',
        lastName: 'Vargas',
        email: 'PVARGAS',
        phoneNumber: '650.121.2004',
        hireDate: new Date('1998-07-09'),
        jobId: 'ST_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 145,
        firstName: 'John',
        lastName: 'Russell',
        email: 'JRUSSEL',
        phoneNumber: '011.44.1344.429268',
        hireDate: new Date('1996-10-01'),
        jobId: 'SA_MAN',
        salary: 14000,
        commissionPct: 0.4,
        managerId: 100,
        departmentId: 80,
      },
      {
        employeeId: 146,
        firstName: 'Karen',
        lastName: 'Partners',
        email: 'KPARTNER',
        phoneNumber: '011.44.1344.467268',
        hireDate: new Date('1997-01-05'),
        jobId: 'SA_MAN',
        salary: 13500,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        employeeId: 147,
        firstName: 'Alberto',
        lastName: 'Errazuriz',
        email: 'AERRAZUR',
        phoneNumber: '011.44.1344.429278',
        hireDate: new Date('1997-03-10'),
        jobId: 'SA_MAN',
        salary: 12000,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        employeeId: 148,
        firstName: 'Gerald',
        lastName: 'Cambrault',
        email: 'GCAMBRAU',
        phoneNumber: '011.44.1344.619268',
        hireDate: new Date('1999-10-15'),
        jobId: 'SA_MAN',
        salary: 11000,
        commissionPct: 0.3,
        managerId: 100,
        departmentId: 80,
      },
      {
        employeeId: 149,
        firstName: 'Eleni',
        lastName: 'Zlotkey',
        email: 'EZLOTKEY',
        phoneNumber: '011.44.1344.429018',
        hireDate: new Date('2000-01-29'),
        jobId: 'SA_MAN',
        salary: 10500,
        commissionPct: 0.2,
        managerId: 100,
        departmentId: 80,
      },
      {
        employeeId: 150,
        firstName: 'Peter',
        lastName: 'Tucker',
        email: 'PTUCKER',
        phoneNumber: '011.44.1344.129268',
        hireDate: new Date('1997-03-02'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.3,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 151,
        firstName: 'David',
        lastName: 'Bernstein',
        email: 'DBERNSTE',
        phoneNumber: '011.44.1344.345268',
        hireDate: new Date('1999-02-24'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.25,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 152,
        firstName: 'Peter',
        lastName: 'Hall',
        email: 'PHALL',
        phoneNumber: '011.44.1344.478968',
        hireDate: new Date('1998-01-20'),
        jobId: 'SA_REP',
        salary: 9000,
        commissionPct: 0.25,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 153,
        firstName: 'Christopher',
        lastName: 'Olsen',
        email: 'COLSEN',
        phoneNumber: '011.44.1344.498718',
        hireDate: new Date('1999-03-30'),
        jobId: 'SA_REP',
        salary: 8000,
        commissionPct: 0.2,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 154,
        firstName: 'Nanette',
        lastName: 'Cambrault',
        email: 'NCAMBRAU',
        phoneNumber: '011.44.1344.987668',
        hireDate: new Date('2000-12-09'),
        jobId: 'SA_REP',
        salary: 7500,
        commissionPct: 0.2,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 155,
        firstName: 'Oliver',
        lastName: 'Tuvault',
        email: 'OTUVAULT',
        phoneNumber: '011.44.1344.486508',
        hireDate: new Date('1997-11-23'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.15,
        managerId: 145,
        departmentId: 80,
      },
      {
        employeeId: 156,
        firstName: 'Janette',
        lastName: 'King',
        email: 'JKING',
        phoneNumber: '011.44.1344.456738',
        hireDate: new Date('1998-01-30'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 157,
        firstName: 'Patrick',
        lastName: 'Sully',
        email: 'PSULLY',
        phoneNumber: '011.44.1344.429268',
        hireDate: new Date('1999-03-04'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 158,
        firstName: 'Allan',
        lastName: 'McEwen',
        email: 'AMCEWEN',
        phoneNumber: '011.44.1344.345268',
        hireDate: new Date('1999-08-01'),
        jobId: 'SA_REP',
        salary: 9000,
        commissionPct: 0.35,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 159,
        firstName: 'Lindsey',
        lastName: 'Smith',
        email: 'LSMITH',
        phoneNumber: '011.44.1344.467897',
        hireDate: new Date('2000-03-10'),
        jobId: 'SA_REP',
        salary: 8000,
        commissionPct: 0.3,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 160,
        firstName: 'Louise',
        lastName: 'Doran',
        email: 'LDORAN',
        phoneNumber: '011.44.1344.467890',
        hireDate: new Date('2000-12-15'),
        jobId: 'SA_REP',
        salary: 7500,
        commissionPct: 0.3,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 161,
        firstName: 'Sarath',
        lastName: 'Sewall',
        email: 'SSEWALL',
        phoneNumber: '650.507.9844',
        hireDate: new Date('1998-11-23'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.25,
        managerId: 146,
        departmentId: 80,
      },
      {
        employeeId: 162,
        firstName: 'Clara',
        lastName: 'Vishney',
        email: 'CVISHNEY',
        phoneNumber: '650.507.9877',
        hireDate: new Date('1999-11-11'),
        jobId: 'SA_REP',
        salary: 10500,
        commissionPct: 0.25,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 163,
        firstName: 'Danielle',
        lastName: 'Greene',
        email: 'DGREENE',
        phoneNumber: '650.507.9878',
        hireDate: new Date('1999-03-19'),
        jobId: 'SA_REP',
        salary: 9500,
        commissionPct: 0.15,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 164,
        firstName: 'Mattea',
        lastName: 'Marvins',
        email: 'MMARVINS',
        phoneNumber: '650.507.9879',
        hireDate: new Date('2000-01-24'),
        jobId: 'SA_REP',
        salary: 7200,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 165,
        firstName: 'David',
        lastName: 'Lee',
        email: 'DLEE',
        phoneNumber: '650.507.9880',
        hireDate: new Date('1997-02-23'),
        jobId: 'SA_REP',
        salary: 6800,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 166,
        firstName: 'Sundar',
        lastName: 'Ande',
        email: 'SANDE',
        phoneNumber: '650.507.9881',
        hireDate: new Date('2000-03-24'),
        jobId: 'SA_REP',
        salary: 6400,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 167,
        firstName: 'Amit',
        lastName: 'Banda',
        email: 'ABANDA',
        phoneNumber: '650.507.9882',
        hireDate: new Date('1996-04-21'),
        jobId: 'SA_REP',
        salary: 6200,
        commissionPct: 0.1,
        managerId: 147,
        departmentId: 80,
      },
      {
        employeeId: 168,
        firstName: 'Lisa',
        lastName: 'Ozer',
        email: 'LOZER',
        phoneNumber: '650.507.9883',
        hireDate: new Date('1997-03-11'),
        jobId: 'SA_REP',
        salary: 11500,
        commissionPct: 0.25,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 169,
        firstName: 'Harrison',
        lastName: 'Bloom',
        email: 'HBLOOM',
        phoneNumber: '650.507.9884',
        hireDate: new Date('1997-03-23'),
        jobId: 'SA_REP',
        salary: 10000,
        commissionPct: 0.2,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 170,
        firstName: 'Tayler',
        lastName: 'Fox',
        email: 'TFOX',
        phoneNumber: '650.507.9885',
        hireDate: new Date('1998-01-24'),
        jobId: 'SA_REP',
        salary: 9600,
        commissionPct: 0.2,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 171,
        firstName: 'William',
        lastName: 'Smith',
        email: 'WSMITH',
        phoneNumber: '650.507.9886',
        hireDate: new Date('1997-02-23'),
        jobId: 'SA_REP',
        salary: 7400,
        commissionPct: 0.15,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 172,
        firstName: 'Elizabeth',
        lastName: 'Bates',
        email: 'EBATES',
        phoneNumber: '011.44.1344.987777',
        hireDate: new Date('1999-03-15'),
        jobId: 'SA_REP',
        salary: 7300,
        commissionPct: 0.15,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 173,
        firstName: 'Sundita',
        lastName: 'Kumar',
        email: 'SKUMAR',
        phoneNumber: '011.44.1344.987778',
        hireDate: new Date('2000-04-03'),
        jobId: 'SA_REP',
        salary: 6100,
        commissionPct: 0.1,
        managerId: 148,
        departmentId: 80,
      },
      {
        employeeId: 174,
        firstName: 'Ellen',
        lastName: 'Abel',
        email: 'EABEL',
        phoneNumber: '011.44.1644.987779',
        hireDate: new Date('1996-05-11'),
        jobId: 'SA_REP',
        salary: 11000,
        commissionPct: 0.3,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 175,
        firstName: 'Alyssa',
        lastName: 'Hutton',
        email: 'AHUTTON',
        phoneNumber: '011.44.1644.987780',
        hireDate: new Date('1997-03-19'),
        jobId: 'SA_REP',
        salary: 8800,
        commissionPct: 0.25,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 176,
        firstName: 'Jonathon',
        lastName: 'Taylor',
        email: 'JTAYLOR',
        phoneNumber: '011.44.1644.987781',
        hireDate: new Date('1998-03-24'),
        jobId: 'SA_REP',
        salary: 8600,
        commissionPct: 0.2,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 177,
        firstName: 'Jack',
        lastName: 'Livingston',
        email: 'JLIVING',
        phoneNumber: '011.44.1644.987782',
        hireDate: new Date('1998-04-23'),
        jobId: 'SA_REP',
        salary: 8400,
        commissionPct: 0.2,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 178,
        firstName: 'Kimberely',
        lastName: 'Grant',
        email: 'KGRANT',
        phoneNumber: '011.44.1644.987783',
        hireDate: new Date('1999-05-24'),
        jobId: 'SA_REP',
        salary: 7000,
        commissionPct: 0.15,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 179,
        firstName: 'Charles',
        lastName: 'Johnson',
        email: 'CJOHNSON',
        phoneNumber: '011.44.1644.987784',
        hireDate: new Date('2000-01-04'),
        jobId: 'SA_REP',
        salary: 6200,
        commissionPct: 0.1,
        managerId: 149,
        departmentId: 80,
      },
      {
        employeeId: 180,
        firstName: 'Winston',
        lastName: 'Taylor',
        email: 'WTAYLOR',
        phoneNumber: '650.507.9876',
        hireDate: new Date('1998-01-24'),
        jobId: 'SH_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 181,
        firstName: 'Jean',
        lastName: 'Fleaur',
        email: 'JFLEAUR',
        phoneNumber: '650.507.9877',
        hireDate: new Date('1998-02-23'),
        jobId: 'SH_CLERK',
        salary: 3100,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 182,
        firstName: 'Martha',
        lastName: 'Sullivan',
        email: 'MSULLIVAN',
        phoneNumber: '650.507.9878',
        hireDate: new Date('1999-07-21'),
        jobId: 'SH_CLERK',
        salary: 3000,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 183,
        firstName: 'Girard',
        lastName: 'Geoni',
        email: 'GGEONI',
        phoneNumber: '650.507.9879',
        hireDate: new Date('1999-08-26'),
        jobId: 'SH_CLERK',
        salary: 2800,
        commissionPct: null,
        managerId: 120,
        departmentId: 50,
      },
      {
        employeeId: 184,
        firstName: 'Nandita',
        lastName: 'Sarchand',
        email: 'NSARCHAN',
        phoneNumber: '650.509.1876',
        hireDate: new Date('2000-01-27'),
        jobId: 'SH_CLERK',
        salary: 4200,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 185,
        firstName: 'Alexis',
        lastName: 'Bull',
        email: 'ABULL',
        phoneNumber: '650.509.2876',
        hireDate: new Date('1998-02-20'),
        jobId: 'SH_CLERK',
        salary: 4100,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 186,
        firstName: 'Julia',
        lastName: 'Dellinger',
        email: 'JDELLING',
        phoneNumber: '650.509.3876',
        hireDate: new Date('1999-06-24'),
        jobId: 'SH_CLERK',
        salary: 3400,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 187,
        firstName: 'Anthony',
        lastName: 'Cabrio',
        email: 'ACABRIO',
        phoneNumber: '650.509.4876',
        hireDate: new Date('2000-02-07'),
        jobId: 'SH_CLERK',
        salary: 3000,
        commissionPct: null,
        managerId: 121,
        departmentId: 50,
      },
      {
        employeeId: 188,
        firstName: 'Kelly',
        lastName: 'Chung',
        email: 'KCHUNG',
        phoneNumber: '650.505.1876',
        hireDate: new Date('1999-06-07'),
        jobId: 'SH_CLERK',
        salary: 3800,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 189,
        firstName: 'Jennifer',
        lastName: 'Dilly',
        email: 'JDILLY',
        phoneNumber: '650.505.2876',
        hireDate: new Date('1999-08-13'),
        jobId: 'SH_CLERK',
        salary: 3600,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 190,
        firstName: 'Timothy',
        lastName: 'Gates',
        email: 'TGATES',
        phoneNumber: '650.505.3876',
        hireDate: new Date('2000-07-11'),
        jobId: 'SH_CLERK',
        salary: 2900,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 191,
        firstName: 'Randall',
        lastName: 'Perkins',
        email: 'RPERKINS',
        phoneNumber: '650.505.4876',
        hireDate: new Date('1999-12-19'),
        jobId: 'SH_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 122,
        departmentId: 50,
      },
      {
        employeeId: 192,
        firstName: 'Sarah',
        lastName: 'Bell',
        email: 'SBELL',
        phoneNumber: '650.501.1876',
        hireDate: new Date('1996-02-04'),
        jobId: 'SH_CLERK',
        salary: 4000,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 193,
        firstName: 'Britney',
        lastName: 'Everett',
        email: 'BEVERETT',
        phoneNumber: '650.501.2876',
        hireDate: new Date('1997-03-03'),
        jobId: 'SH_CLERK',
        salary: 3900,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 194,
        firstName: 'Samuel',
        lastName: 'McCain',
        email: 'SMCCAIN',
        phoneNumber: '650.501.3876',
        hireDate: new Date('1998-07-01'),
        jobId: 'SH_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 195,
        firstName: 'Kathy',
        lastName: 'McGinnis',
        email: 'KMcGinnis',
        phoneNumber: '650.501.4876',
        hireDate: new Date('1999-06-17'),
        jobId: 'SH_CLERK',
        salary: 2700,
        commissionPct: null,
        managerId: 123,
        departmentId: 50,
      },
      {
        employeeId: 196,
        firstName: 'Kimberely',
        lastName: 'Grant',
        email: 'KGRANT',
        phoneNumber: '650.501.6000',
        hireDate: new Date('1999-05-24'),
        jobId: 'SH_CLERK',
        salary: 2500,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 197,
        firstName: 'Charles',
        lastName: 'Johnson',
        email: 'CJOHNSON',
        phoneNumber: '650.501.8000',
        hireDate: new Date('2000-01-04'),
        jobId: 'SH_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 198,
        firstName: 'Winston',
        lastName: 'Taylor',
        email: 'WTAYLOR',
        phoneNumber: '650.501.9000',
        hireDate: new Date('1998-01-24'),
        jobId: 'SH_CLERK',
        salary: 3200,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 199,
        firstName: 'Jean',
        lastName: 'Fleaur',
        email: 'JFLEAUR',
        phoneNumber: '650.501.1876',
        hireDate: new Date('1998-02-23'),
        jobId: 'SH_CLERK',
        salary: 3100,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 200,
        firstName: 'Martha',
        lastName: 'Sullivan',
        email: 'MSULLIVAN',
        phoneNumber: '650.501.2876',
        hireDate: new Date('1999-07-21'),
        jobId: 'SH_CLERK',
        salary: 3000,
        commissionPct: null,
        managerId: 124,
        departmentId: 50,
      },
      {
        employeeId: 201,
        firstName: 'Michael',
        lastName: 'Hartstein',
        email: 'MHARTSTE',
        phoneNumber: '515.123.5555',
        hireDate: new Date('1999-07-23'),
        jobId: 'MK_MAN',
        salary: 13000,
        commissionPct: null,
        managerId: 100,
        departmentId: 20,
      },
    ];

    const jobHistoryList = [
      {
        employeeId: 102,
        startDate: '13-Jan-1993',
        endDate: '24-Jul-1998',
        jobId: 'IT_PROG',
        departmentId: 60,
      },
      {
        employeeId: 101,
        startDate: '21-Sep-1989',
        endDate: '27-Oct-1993',
        jobId: 'AC_ACCOUNT',
        departmentId: 110,
      },
      {
        employeeId: 101,
        startDate: '28-Oct-1993',
        endDate: '15-Mar-1997',
        jobId: 'AC_MGR',
        departmentId: 110,
      },
      {
        employeeId: 201,
        startDate: '27-Feb-1996',
        endDate: '19-Dec-1999',
        jobId: 'MK_REP',
        departmentId: 20,
      },
      {
        employeeId: 114,
        startDate: '24-Mar-1998',
        endDate: '31-Dec-1999',
        jobId: 'ST_CLERK',
        departmentId: 50,
      },
      {
        employeeId: 122,
        startDate: '01-Jan-1999',
        endDate: '31-Dec-1999',
        jobId: 'ST_CLERK',
        departmentId: 50,
      },
      {
        employeeId: 200,
        startDate: '17-Sep-1987',
        endDate: '17-Jun-1993',
        jobId: 'AD_ASST',
        departmentId: 90,
      },
      {
        employeeId: 176,
        startDate: '24-Mar-1998',
        endDate: '31-Dec-1998',
        jobId: 'SA_REP',
        departmentId: 80,
      },
      {
        employeeId: 176,
        startDate: '01-Jan-1999',
        endDate: '31-Dec-1999',
        jobId: 'SA_MAN',
        departmentId: 80,
      },
      {
        employeeId: 200,
        startDate: '01-Jul-1994',
        endDate: '31-Dec-1998',
        jobId: 'AC_ACCOUNT',
        departmentId: 90,
      },
    ];

    const queryRunner = dataSource.createQueryRunner();
    await queryRunner.startTransaction();

    try {
      await this.insertData(queryRunner, Region, regionList);
      await this.insertData(queryRunner, Country, countryList);
      await this.insertData(queryRunner, Location, locationList);
      await this.insertData(queryRunner, Department, departmentList);
      await this.insertData(queryRunner, Job, jobList);
      await this.insertData(queryRunner, Employee, employeeList);
      await this.insertData(queryRunner, JobHistory, jobHistoryList);

      await queryRunner.commitTransaction();
    } catch (error) {
      await queryRunner.rollbackTransaction();
      throw error;
    } finally {
      await queryRunner.release();
    }
  }

  private async insertData(
    queryRunner: QueryRunner,
    model: ClassConstructor<BaseTimeEntity>,
    data: any[],
  ): Promise<void> {
    const modelInstance = queryRunner.manager.getRepository(model);

    // 데이터 삽입
    await modelInstance.insert(data);
  }
}
